-- Nuxon 4 OS — AI Organization Operating Console
-- Copyright (c) 2024-2026 CL-j-nc. All Rights Reserved.
-- Licensed under the Business Source License 1.1 (BSL). See LICENSE file.

-- ═══════════════════════════════════════════════════════════
-- Migration V2: Multi-Tenant Schema
-- Cloudflare Event Bus → No-Code AI Agent Platform
-- ═══════════════════════════════════════════════════════════

-- ─── 1. Tenants ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tenants (
  id TEXT PRIMARY KEY,              -- uuid
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  plan TEXT DEFAULT 'free',         -- free | pro | enterprise
  token_budget_daily INTEGER DEFAULT 5000,
  tokens_used_today INTEGER DEFAULT 0,
  tokens_reset_at INTEGER,
  webhook_secret TEXT,              -- per-tenant webhook signing secret
  status TEXT DEFAULT 'active',     -- active | suspended | deleted
  created_at INTEGER NOT NULL,
  updated_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_tenants_email ON tenants(email);
CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants(status);

-- ─── 2. Agents (each tenant can have multiple agents) ─────
CREATE TABLE IF NOT EXISTS agents (
  id TEXT PRIMARY KEY,              -- uuid
  tenant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'active',     -- active | paused | deleted
  model_preference TEXT DEFAULT 'auto',  -- auto | fast | strong
  token_budget INTEGER DEFAULT 1000,
  created_at INTEGER NOT NULL,
  updated_at INTEGER,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE INDEX IF NOT EXISTS idx_agents_tenant ON agents(tenant_id, status);

-- ─── 3. Connections (data sources per tenant) ─────────────
CREATE TABLE IF NOT EXISTS connections (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  name TEXT NOT NULL,               -- display name: "My GitHub"
  provider TEXT NOT NULL,           -- github | stripe | telegram | notion | webhook | ...
  config_json TEXT,                 -- provider-specific config (encrypted)
  webhook_path TEXT,                -- unique inbound path: /wh/:tenant_id/:connection_id
  verify_secret TEXT,               -- signature verification secret
  status TEXT DEFAULT 'active',     -- active | paused | error
  last_event_at INTEGER,
  event_count INTEGER DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE INDEX IF NOT EXISTS idx_conn_tenant ON connections(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_conn_webhook ON connections(webhook_path);

-- ─── 4. User Rules (replaces hardcoded rules.js) ─────────
-- TODO: This is where you define the rule structure for the no-code UI
-- See design notes below the table
CREATE TABLE IF NOT EXISTS user_rules (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  name TEXT NOT NULL,               -- "Ignore small price changes"
  priority INTEGER DEFAULT 100,     -- lower = higher priority
  enabled INTEGER DEFAULT 1,

  -- Condition (WHEN)
  source TEXT,                      -- connection provider or '*'
  event_type TEXT,                  -- event type or '*'
  condition_json TEXT,              -- additional conditions (see below)

  -- Action (THEN)
  action TEXT NOT NULL,             -- execute | ignore | defer | notify
  target TEXT,                      -- target worker or connection
  action_params_json TEXT,          -- action-specific parameters

  -- Metadata
  origin TEXT DEFAULT 'user',       -- user | learned (auto-generated by AI)
  learned_from INTEGER DEFAULT 0,   -- how many AI decisions this was learned from
  success_rate REAL,
  hit_count INTEGER DEFAULT 0,      -- how many times this rule fired
  last_hit_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  FOREIGN KEY (agent_id) REFERENCES agents(id)
);

CREATE INDEX IF NOT EXISTS idx_rules_tenant ON user_rules(tenant_id, agent_id, enabled);
CREATE INDEX IF NOT EXISTS idx_rules_source ON user_rules(source, event_type);
CREATE INDEX IF NOT EXISTS idx_rules_origin ON user_rules(origin);

-- ─── 5. Events (multi-tenant) ────────────────────────────
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  connection_id TEXT,
  source TEXT,
  env TEXT DEFAULT 'production',
  payload TEXT,
  status TEXT DEFAULT 'pending',
  created_at INTEGER,
  updated_at INTEGER,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE INDEX IF NOT EXISTS idx_events_tenant ON events(tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_source ON events(tenant_id, source);
CREATE INDEX IF NOT EXISTS idx_events_status ON events(tenant_id, status);

-- ─── 6. AI Decisions (multi-tenant) ──────────────────────
CREATE TABLE IF NOT EXISTS ai_decisions (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  event_id TEXT,
  source TEXT,
  action TEXT,
  target TEXT,
  confidence REAL,
  reason TEXT,
  plan TEXT,
  result TEXT DEFAULT 'pending',
  decided_by TEXT,                  -- rule_engine | ai | budget_controller
  model_used TEXT,
  tokens_used INTEGER DEFAULT 0,
  created_at INTEGER,
  completed_at INTEGER,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE INDEX IF NOT EXISTS idx_dec_tenant ON ai_decisions(tenant_id, agent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_dec_event ON ai_decisions(event_id);
CREATE INDEX IF NOT EXISTS idx_dec_source ON ai_decisions(tenant_id, source, action);

-- ─── 7. AI Memory (multi-tenant) ─────────────────────────
CREATE TABLE IF NOT EXISTS ai_memory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  category TEXT,
  key TEXT,
  value TEXT,
  score REAL,
  created_at INTEGER,
  expires_at INTEGER,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE INDEX IF NOT EXISTS idx_mem_tenant ON ai_memory(tenant_id, agent_id, category);
CREATE INDEX IF NOT EXISTS idx_mem_expires ON ai_memory(expires_at);

-- ─── 8. Model Logs (multi-tenant + per agent) ────────────
CREATE TABLE IF NOT EXISTS ai_model_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tenant_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  model TEXT,
  tokens_in INTEGER,
  tokens_out INTEGER,
  latency_ms INTEGER,
  success INTEGER,
  created_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_mlogs_tenant ON ai_model_logs(tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_mlogs_model ON ai_model_logs(model);

-- ─── 9. Sensor Events (multi-tenant) ─────────────────────
CREATE TABLE IF NOT EXISTS sensor_events (
  event_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  trace_id TEXT,
  span_id TEXT,
  parent_span_id TEXT,
  task_id TEXT,
  run_id TEXT,
  source TEXT NOT NULL,
  agent_id TEXT,
  sensor_id TEXT,
  env TEXT DEFAULT 'production',
  ts INTEGER NOT NULL,
  type TEXT NOT NULL,
  stage TEXT,
  status TEXT,
  progress REAL,
  payload_json TEXT,
  metrics_json TEXT,
  error_json TEXT,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE INDEX IF NOT EXISTS idx_se_tenant ON sensor_events(tenant_id, ts);
CREATE INDEX IF NOT EXISTS idx_se_source ON sensor_events(tenant_id, source);
CREATE INDEX IF NOT EXISTS idx_se_trace ON sensor_events(trace_id);

-- ─── 10. Proposals (multi-tenant) ────────────────────────
CREATE TABLE IF NOT EXISTS proposals (
  proposal_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  ts INTEGER NOT NULL,
  kind TEXT NOT NULL,
  confidence REAL DEFAULT 0.5,
  summary TEXT,
  data_json TEXT,
  status TEXT DEFAULT 'new',
  FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE INDEX IF NOT EXISTS idx_prop_tenant ON proposals(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_prop_ts ON proposals(ts);
